---
title: "18 janvier 2023"
---

## Introduction au cours “Identités numériques”

Bienvenue à toutes et à tous à notre premier cours sur les Identités numériques.

::: {.callout-note}

[Cliquez ici](https://demo.hedgedoc.org/vT4VGOsATByXrgmU8gkaMw) pour accéder au pad collaboratif.

:::


## Déroulé de la séance

- Présentation du site web et des ressources ;
- Présentation du plan du cours ;
- Exercice 1 ;
- Introduction à la notion d'identité numérique ;
- Présentation de la séance du 25 janvier ;
- Questions.

## Exercice 1

1. Définir en une phrase l'identité numérique.

## Définitions

::: {.callout-tip collapse="true"}

### Identité numérique - O. Ertzscheid

> L’identité numérique est constituée de la somme des traces numériques se rapportant à un individu ou à une collectivité : des traces « profilaires » correspondant à ce que je dis de moi (qui suis-je ?) ; des traces « navigationnelles » qui renseignent sur les sites que je fréquente et sur lesquels je commente ou j’achète (comment je me comporte) ; enfin des traces inscriptibles et déclaratives – ce que je publie sur mon blog par exemple – qui reflètent directement mes idées et mes opinions (ce que je pense).  
> De manière plus circonstanciée, l’identité numérique peut être définie comme la collection des traces (écrits, contenus audios ou vidéos, messages sur des forums, identifiants de connexion, etc.) que nous laissons derrière nous, consciemment ou inconsciemment, au fil de nos navigations sur le réseau et le reflet de cet ensemble de traces, tel qu’il apparaît « remixé » par les moteurs de recherche.  

Olivier Ertzscheid, *Qu'est-ce que l'identité numérique ?*

:::

::: {.callout-tip collapse="true"}

### Identité Numérique - D. Cardon

> L’identité numérique est un processus collectif : les participants montrent d’eux des signes que les autres approuvent plutôt que des signes qui ne retiennent pas leur attention. Leur identité est produite par le réseau social d’amis qu’ils ont choisi, par leur utilisation de telle ou telle plateforme, par le fait qu’ils s’exposent aux commentaires et aux likes de personnes qui, elles-mêmes, exposent et privilégient tel ou tel trait de leur propre identité. Bref, leur identité numérique n’appartient pas totalement aux individus. Elle est la conséquence de l’espace social dans lequel ils interagissent.  

Dominique Cardon, "Identité en ligne".

:::

## Lectures de la semaine

### Lecture obligatoire

- Ertzscheid, O. (2013). "Les logiques identitaires". Dans *Qu’est-ce que l’identité numérique ?*. OpenEdition Press. https://books.openedition.org/oep/405

### Lecture optionnelle

- Cardon, D. (2019). Identité en ligne. Dans Culture numérique (p. 176‑188). Presses de Sciences Po. https://www.cairn.info/culture-numerique--9782724623659-p-176.htm

## Pour la semaine prochaine

- Désigner deux Secrétaires pour les notes collaboratives.

Exercice : 

1. Réaliser le tutoriel du langage de balisage Markdown : https://www.arthurperret.fr/tutomd/tutorial/tutorial.html ;
2. Se présenter en 3 lignes dans le pad du 18 janvier 2023.

::: {.callout-caution}

Attention à ne pas effacer les informations ajoutées par les autres étudiant·e·s !

:::